#/etc/dnsmasq.d/lan.conf
interface=eth1
bind-interfaces
except-interface=lo
except-interface=eth0
dhcp-range=[REDACTED SUBNET].100,[REDACTED SUBNET].199,255.255.255.0,12h
dhcp-option=option:router,[REDACTED SUBNET].1
dhcp-option=option:dns-server,[REDACTED SUBNET].1
server=1.1.1.1
server=9.9.9.9
domain=home
